owner: bbmri-eric 
repo: status

sites:
  - name: BBMRI-ERIC
    url: https://bbmri-eric.eu
  - name: Negotiator
    url: https://negotiator.bbmri-eric.eu
  - name: Directory
    url: https://directory.bbmri-eric.eu
  - name: Locator
    url: https://locator.bbmri-eric.eu
  - name: Finder
    url: https://finder.bbmri-eric.eu

status-website:
  cname: status.bbmri-eric.eu
  theme: light
  logoUrl: https://www.bbmri-eric.eu/wp-content/themes/bbmri-eric/img/BBMRI-ERIC-gateway-for-health.svg
  favicon: https://www.bbmri-eric.eu/wp-content/uploads/favicon.png
  name: BBMRI-ERIC Status
  introTitle: "**BBMRI-ERIC Status page**"
  introMessage: This is a status page for BBMRI-ERIC services. If you encounter downgraded performance in any of the services and it is not reported here, please email us at it@helpdesk.bbmri-eric.eu
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
