owner: bbmri-eric 
repo: status

sites:
  - name: BBMRI-ERIC
    url: https://www.bbmri-eric.eu
  - name: Negotiator
    url: https://negotiator.bbmri-eric.eu
  - name: Directory
    url: https://directory.bbmri-eric.eu
  - name: Helpdesk
    url: https://helpdesk.bbmri-eric.eu/RT
  - name: LifeScience Login
    url: https://login.aai.lifescience-ri.eu/oidc/.well-known/openid-configuration
    icon: https://lifescience-ri.eu/fileadmin/lifescience-ri/media/Images/login-grey-wide.jpg.png
  - name: LifeScience Login IdM (Perun)
    url: https://perun.aai.lifescience-ri.eu
    icon: https://perun.aai.lifescience-ri.eu/assets/img/perun.ico
  - name: Locator
    url: https://locator.bbmri-eric.eu
  - name: BBMRI.de Sample Locator
    url: https://samplelocator.bbmri.de
  - name: BBMRI.cz Data Catalogue
    url: https://data.bbmri.cz


status-website:
  cname: status.bbmri-eric.eu
  theme: light
  logoUrl: https://www.bbmri-eric.eu/wp-content/themes/bbmri-eric/img/BBMRI-ERIC-gateway-for-health.svg
  favicon: https://www.bbmri-eric.eu/wp-content/uploads/favicon.png
  name: BBMRI-ERIC Status
  introTitle: "**BBMRI-ERIC Status page**"
  introMessage: This is a status page for BBMRI-ERIC services. If you encounter downgraded performance in any of the services and it is not reported here, please email us at it@helpdesk.bbmri-eric.eu
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
